/**
 * IMPORTANT: Loading glTF models into a Three.js scene is a lot of work.
 * Before we can configure or animate our model’s meshes, we need to iterate through
 * each part of our model’s meshes and save them separately.
 *
 * But luckily there is an app that turns gltf or glb files into jsx components
 * For this model, visit https://gltf.pmnd.rs/
 * And get the code. And then add the rest of the things.
 * YOU DON'T HAVE TO WRITE EVERYTHING FROM SCRATCH
 */

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from "../assets/3d/Robot_Tarot_GLTF_Flag_Cali_02.glb";

export function Robot_Tarot_GLTF_Flag_Cali_02({ currentAnimation, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  // This effect will run whenever the currentAnimation prop changes
  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Material}
        />
        <mesh
          name="path2001"
          castShadow
          receiveShadow
          geometry={nodes.path2001.geometry}
          material={materials['SVGMat.039']}
        />
        <mesh
          name="path4001"
          castShadow
          receiveShadow
          geometry={nodes.path4001.geometry}
          material={materials['SVGMat.041']}
        />
        <mesh
          name="path5-8-4-0-5001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-0-5001'].geometry}
          material={materials['SVGMat.070']}
        />
        <mesh
          name="path5-8-4-00-6001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-00-6001'].geometry}
          material={materials['SVGMat.073']}
        />
        <mesh
          name="path5-8-4-1-0001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-1-0001'].geometry}
          material={materials['SVGMat.058']}
        />
        <mesh
          name="path5-8-4-2-7001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-2-7001'].geometry}
          material={materials['SVGMat.061']}
        />
        <mesh
          name="path5-8-4-3-5001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-3-5001'].geometry}
          material={materials['SVGMat.055']}
        />
        <mesh
          name="path5-8-4-4-5001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-4-5001'].geometry}
          material={materials['SVGMat.056']}
        />
        <mesh
          name="path5-8-4-5-5001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-5-5001'].geometry}
          material={materials['SVGMat.067']}
        />
        <mesh
          name="path5-8-4-6-1001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-6-1001'].geometry}
          material={materials['SVGMat.062']}
        />
        <mesh
          name="path5-8-4-06-4001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-06-4001'].geometry}
          material={materials['SVGMat.060']}
        />
        <mesh
          name="path5-8-4-7-3001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-7-3001'].geometry}
          material={materials['SVGMat.071']}
        />
        <mesh
          name="path5-8-4-8-9001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-8-9001'].geometry}
          material={materials['SVGMat.054']}
        />
        <mesh
          name="path5-8-4-9-7001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-9-7001'].geometry}
          material={materials['SVGMat.072']}
        />
        <mesh
          name="path5-8-4-27-6001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-27-6001'].geometry}
          material={materials['SVGMat.064']}
        />
        <mesh
          name="path5-8-4-29-8001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-29-8001'].geometry}
          material={materials['SVGMat.065']}
        />
        <mesh
          name="path5-8-4-33-3001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-33-3001'].geometry}
          material={materials['SVGMat.057']}
        />
        <mesh
          name="path5-8-4-42-6001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-42-6001'].geometry}
          material={materials['SVGMat.059']}
        />
        <mesh
          name="path5-8-4-49001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-49001'].geometry}
          material={materials['SVGMat.074']}
        />
        <mesh
          name="path5-8-4-65-9001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-65-9001'].geometry}
          material={materials['SVGMat.068']}
        />
        <mesh
          name="path5-8-4-82-7001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-82-7001'].geometry}
          material={materials['SVGMat.066']}
        />
        <mesh
          name="path5-8-4-88-7001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-88-7001'].geometry}
          material={materials['SVGMat.063']}
        />
        <mesh
          name="path5-8-4-277-5001"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-277-5001'].geometry}
          material={materials['SVGMat.069']}
        />
        <mesh
          name="path7001"
          castShadow
          receiveShadow
          geometry={nodes.path7001.geometry}
          material={materials['SVGMat.043']}
        />
        <mesh
          name="path9001"
          castShadow
          receiveShadow
          geometry={nodes.path9001.geometry}
          material={materials['SVGMat.044']}
        />
        <mesh
          name="path11001"
          castShadow
          receiveShadow
          geometry={nodes.path11001.geometry}
          material={materials['SVGMat.045']}
        />
        <mesh
          name="path13001"
          castShadow
          receiveShadow
          geometry={nodes.path13001.geometry}
          material={materials['SVGMat.046']}
        />
        <mesh
          name="path15001"
          castShadow
          receiveShadow
          geometry={nodes.path15001.geometry}
          material={materials['SVGMat.047']}
        />
        <mesh
          name="path2"
          castShadow
          receiveShadow
          geometry={nodes.path2.geometry}
          material={materials['SVGMat.039']}
        />
        <mesh
          name="path4"
          castShadow
          receiveShadow
          geometry={nodes.path4.geometry}
          material={materials['SVGMat.041']}
        />
        <mesh
          name="path7"
          castShadow
          receiveShadow
          geometry={nodes.path7.geometry}
          material={materials['SVGMat.043']}
        />
        <mesh
          name="path9"
          castShadow
          receiveShadow
          geometry={nodes.path9.geometry}
          material={materials['SVGMat.044']}
        />
        <mesh
          name="path11"
          castShadow
          receiveShadow
          geometry={nodes.path11.geometry}
          material={materials['SVGMat.045']}
        />
        <mesh
          name="path13"
          castShadow
          receiveShadow
          geometry={nodes.path13.geometry}
          material={materials['SVGMat.046']}
        />
        <mesh
          name="path15"
          castShadow
          receiveShadow
          geometry={nodes.path15.geometry}
          material={materials['SVGMat.047']}
        />
        <mesh
          name="path5-8-4-8-9"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-8-9'].geometry}
          material={materials['SVGMat.054']}
        />
        <mesh
          name="path5-8-4-3-5"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-3-5'].geometry}
          material={materials['SVGMat.055']}
        />
        <mesh
          name="path5-8-4-4-5"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-4-5'].geometry}
          material={materials['SVGMat.056']}
        />
        <mesh
          name="path5-8-4-33-3"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-33-3'].geometry}
          material={materials['SVGMat.057']}
        />
        <mesh
          name="path5-8-4-1-0"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-1-0'].geometry}
          material={materials['SVGMat.058']}
        />
        <mesh
          name="path5-8-4-42-6"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-42-6'].geometry}
          material={materials['SVGMat.059']}
        />
        <mesh
          name="path5-8-4-06-4"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-06-4'].geometry}
          material={materials['SVGMat.060']}
        />
        <mesh
          name="path5-8-4-2-7"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-2-7'].geometry}
          material={materials['SVGMat.061']}
        />
        <mesh
          name="path5-8-4-6-1"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-6-1'].geometry}
          material={materials['SVGMat.062']}
        />
        <mesh
          name="path5-8-4-88-7"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-88-7'].geometry}
          material={materials['SVGMat.063']}
        />
        <mesh
          name="path5-8-4-27-6"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-27-6'].geometry}
          material={materials['SVGMat.064']}
        />
        <mesh
          name="path5-8-4-29-8"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-29-8'].geometry}
          material={materials['SVGMat.065']}
        />
        <mesh
          name="path5-8-4-82-7"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-82-7'].geometry}
          material={materials['SVGMat.066']}
        />
        <mesh
          name="path5-8-4-5-5"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-5-5'].geometry}
          material={materials['SVGMat.067']}
        />
        <mesh
          name="path5-8-4-65-9"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-65-9'].geometry}
          material={materials['SVGMat.068']}
        />
        <mesh
          name="path5-8-4-277-5"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-277-5'].geometry}
          material={materials['SVGMat.069']}
        />
        <mesh
          name="path5-8-4-0-5"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-0-5'].geometry}
          material={materials['SVGMat.070']}
        />
        <mesh
          name="path5-8-4-7-3"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-7-3'].geometry}
          material={materials['SVGMat.071']}
        />
        <mesh
          name="path5-8-4-9-7"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-9-7'].geometry}
          material={materials['SVGMat.072']}
        />
        <mesh
          name="path5-8-4-00-6"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-00-6'].geometry}
          material={materials['SVGMat.073']}
        />
        <mesh
          name="path5-8-4-49"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-49'].geometry}
          material={materials['SVGMat.074']}
        />
        <mesh
          name="path2002"
          castShadow
          receiveShadow
          geometry={nodes.path2002.geometry}
          material={materials['SVGMat.076']}
        />
        <mesh
          name="path2003"
          castShadow
          receiveShadow
          geometry={nodes.path2003.geometry}
          material={materials['SVGMat.039']}
        />
        <mesh
          name="path4002"
          castShadow
          receiveShadow
          geometry={nodes.path4002.geometry}
          material={materials['SVGMat.041']}
        />
        <mesh
          name="path5-8-4-0-5002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-0-5002'].geometry}
          material={materials['SVGMat.070']}
        />
        <mesh
          name="path5-8-4-00-6002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-00-6002'].geometry}
          material={materials['SVGMat.073']}
        />
        <mesh
          name="path5-8-4-1-0002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-1-0002'].geometry}
          material={materials['SVGMat.058']}
        />
        <mesh
          name="path5-8-4-2-7002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-2-7002'].geometry}
          material={materials['SVGMat.061']}
        />
        <mesh
          name="path5-8-4-3-5002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-3-5002'].geometry}
          material={materials['SVGMat.055']}
        />
        <mesh
          name="path5-8-4-4-5002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-4-5002'].geometry}
          material={materials['SVGMat.056']}
        />
        <mesh
          name="path5-8-4-5-5002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-5-5002'].geometry}
          material={materials['SVGMat.067']}
        />
        <mesh
          name="path5-8-4-6-1002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-6-1002'].geometry}
          material={materials['SVGMat.062']}
        />
        <mesh
          name="path5-8-4-06-4002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-06-4002'].geometry}
          material={materials['SVGMat.060']}
        />
        <mesh
          name="path5-8-4-7-3002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-7-3002'].geometry}
          material={materials['SVGMat.071']}
        />
        <mesh
          name="path5-8-4-8-9002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-8-9002'].geometry}
          material={materials['SVGMat.054']}
        />
        <mesh
          name="path5-8-4-9-7002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-9-7002'].geometry}
          material={materials['SVGMat.072']}
        />
        <mesh
          name="path5-8-4-27-6002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-27-6002'].geometry}
          material={materials['SVGMat.064']}
        />
        <mesh
          name="path5-8-4-29-8002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-29-8002'].geometry}
          material={materials['SVGMat.065']}
        />
        <mesh
          name="path5-8-4-33-3002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-33-3002'].geometry}
          material={materials['SVGMat.057']}
        />
        <mesh
          name="path5-8-4-42-6002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-42-6002'].geometry}
          material={materials['SVGMat.059']}
        />
        <mesh
          name="path5-8-4-49002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-49002'].geometry}
          material={materials['SVGMat.074']}
        />
        <mesh
          name="path5-8-4-65-9002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-65-9002'].geometry}
          material={materials['SVGMat.068']}
        />
        <mesh
          name="path5-8-4-82-7002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-82-7002'].geometry}
          material={materials['SVGMat.066']}
        />
        <mesh
          name="path5-8-4-88-7002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-88-7002'].geometry}
          material={materials['SVGMat.063']}
        />
        <mesh
          name="path5-8-4-277-5002"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-277-5002'].geometry}
          material={materials['SVGMat.069']}
        />
        <mesh
          name="path7002"
          castShadow
          receiveShadow
          geometry={nodes.path7002.geometry}
          material={materials['SVGMat.043']}
        />
        <mesh
          name="path9002"
          castShadow
          receiveShadow
          geometry={nodes.path9002.geometry}
          material={materials['SVGMat.044']}
        />
        <mesh
          name="path11002"
          castShadow
          receiveShadow
          geometry={nodes.path11002.geometry}
          material={materials['SVGMat.045']}
        />
        <mesh
          name="path13002"
          castShadow
          receiveShadow
          geometry={nodes.path13002.geometry}
          material={materials['SVGMat.046']}
        />
        <mesh
          name="path15002"
          castShadow
          receiveShadow
          geometry={nodes.path15002.geometry}
          material={materials['SVGMat.047']}
        />
        <mesh
          name="path2004"
          castShadow
          receiveShadow
          geometry={nodes.path2004.geometry}
          material={materials['SVGMat.076']}
        />
        <group name="path2005">
          <mesh
            name="path2005_1"
            castShadow
            receiveShadow
            geometry={nodes.path2005_1.geometry}
            material={materials['SVGMat.039']}
          />
          <mesh
            name="path2005_2"
            castShadow
            receiveShadow
            geometry={nodes.path2005_2.geometry}
            material={materials['SVGMat.041']}
          />
        </group>
        <group name="path4003">
          <mesh
            name="path4003_1"
            castShadow
            receiveShadow
            geometry={nodes.path4003_1.geometry}
            material={materials['SVGMat.041']}
          />
          <mesh
            name="path4003_2"
            castShadow
            receiveShadow
            geometry={nodes.path4003_2.geometry}
            material={materials['SVGMat.039']}
          />
          <mesh
            name="path4003_3"
            castShadow
            receiveShadow
            geometry={nodes.path4003_3.geometry}
            material={materials['SVGMat.073']}
          />
          <mesh
            name="path4003_4"
            castShadow
            receiveShadow
            geometry={nodes.path4003_4.geometry}
            material={materials['SVGMat.058']}
          />
          <mesh
            name="path4003_5"
            castShadow
            receiveShadow
            geometry={nodes.path4003_5.geometry}
            material={materials['SVGMat.071']}
          />
          <mesh
            name="path4003_6"
            castShadow
            receiveShadow
            geometry={nodes.path4003_6.geometry}
            material={materials['SVGMat.072']}
          />
          <mesh
            name="path4003_7"
            castShadow
            receiveShadow
            geometry={nodes.path4003_7.geometry}
            material={materials['SVGMat.057']}
          />
        </group>
        <mesh
          name="path2006"
          castShadow
          receiveShadow
          geometry={nodes.path2006.geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path4004"
          castShadow
          receiveShadow
          geometry={nodes.path4004.geometry}
          material={materials['SVGMat.002']}
        />
        <mesh
          name="path5-8-4-0-5003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-0-5003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-1-0003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-1-0003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-2-7003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-2-7003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-3-5003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-3-5003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-4-5003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-4-5003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-5-5003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-5-5003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-6-1003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-6-1003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-06-4003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-06-4003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-7-3003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-7-3003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-8-9003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-8-9003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-9-7003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-9-7003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-27-6003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-27-6003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-29-8003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-29-8003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-42-6003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-42-6003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-49003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-49003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-65-9003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-65-9003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-82-7003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-82-7003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-88-7003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-88-7003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-277-5003"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-277-5003'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path7003"
          castShadow
          receiveShadow
          geometry={nodes.path7003.geometry}
          material={materials['SVGMat.043']}
        />
        <mesh
          name="path9003"
          castShadow
          receiveShadow
          geometry={nodes.path9003.geometry}
          material={materials['SVGMat.044']}
        />
        <mesh
          name="path11003"
          castShadow
          receiveShadow
          geometry={nodes.path11003.geometry}
          material={materials['SVGMat.045']}
        />
        <mesh
          name="path13003"
          castShadow
          receiveShadow
          geometry={nodes.path13003.geometry}
          material={materials['SVGMat.046']}
        />
        <mesh
          name="path15003"
          castShadow
          receiveShadow
          geometry={nodes.path15003.geometry}
          material={materials['SVGMat.047']}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
        />
        <mesh
          name="path2007"
          castShadow
          receiveShadow
          geometry={nodes.path2007.geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path4005"
          castShadow
          receiveShadow
          geometry={nodes.path4005.geometry}
          material={materials['SVGMat.002']}
        />
        <mesh
          name="path5-8-4-0-5004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-0-5004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-1-0004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-1-0004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-2-7004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-2-7004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-3-5004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-3-5004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-4-5004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-4-5004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-6-1004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-6-1004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-06-4004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-06-4004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-7-3004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-7-3004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-8-9004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-8-9004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-9-7004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-9-7004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-27-6004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-27-6004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-42-6004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-42-6004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-49004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-49004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-65-9004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-65-9004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-88-7004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-88-7004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path5-8-4-277-5004"
          castShadow
          receiveShadow
          geometry={nodes['path5-8-4-277-5004'].geometry}
          material={materials['SVGMat.001']}
        />
        <mesh
          name="path7004"
          castShadow
          receiveShadow
          geometry={nodes.path7004.geometry}
          material={materials['SVGMat.043']}
        />
        <mesh
          name="path9004"
          castShadow
          receiveShadow
          geometry={nodes.path9004.geometry}
          material={materials['SVGMat.044']}
        />
        <mesh
          name="path11004"
          castShadow
          receiveShadow
          geometry={nodes.path11004.geometry}
          material={materials['SVGMat.045']}
        />
        <mesh
          name="path13004"
          castShadow
          receiveShadow
          geometry={nodes.path13004.geometry}
          material={materials['SVGMat.046']}
        />
        <mesh
          name="path15004"
          castShadow
          receiveShadow
          geometry={nodes.path15004.geometry}
          material={materials['SVGMat.047']}
        />
        <mesh
          name="path175"
          castShadow
          receiveShadow
          geometry={nodes.path175.geometry}
          material={materials.SVGMat}
        />
        <group name="Armature" scale={29.282}>
          <group name="pathflag">
            <skinnedMesh
              name="pathflag_1"
              geometry={nodes.pathflag_1.geometry}
              material={materials['SVGMat.002']}
              skeleton={nodes.pathflag_1.skeleton}
            />
            <skinnedMesh
              name="pathflag_2"
              geometry={nodes.pathflag_2.geometry}
              material={materials['SVGMat.001']}
              skeleton={nodes.pathflag_2.skeleton}
            />
            <skinnedMesh
              name="pathflag_3"
              geometry={nodes.pathflag_3.geometry}
              material={materials['SVGMat.003']}
              skeleton={nodes.pathflag_3.skeleton}
            />
          </group>
          <primitive object={nodes.Bone} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(scene);